# Generated by Django 5.2.2 on 2025-06-11 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_category_contact_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
